SET SERVEROUT ON
SET VERIFY OFF

DROP TABLE CONTA_CORRENTE;
create table CONTA_CORRENTE(NUM_CONTA NUMBER(10), NOME_CORRENTISTA VARCHAR2(50), SALDO NUMBER(10,2), TIPO_CONTA NUMBER(1));



INSERT INTO CONTA_CORRENTE VALUES(13254, 'PEDRO CARVALHO', 23000.00, 0);
INSERT INTO CONTA_CORRENTE VALUES(23547, 'EDUARDO SILVA', 2000.00, 1) ;
INSERT INTO CONTA_CORRENTE VALUES(98798, 'LUCAS PEREIRA', 5000.00, 0) ;

DECLARE
CONTA_NUM NUMBER(5) := &NUMEROCONTA;
VL_SACAR NUMBER(10,2) := &SACAR;
V_SALDO NUMBER(10,2);
V_TIPO NUMBER(1);

BEGIN
SELECT SALDO INTO V_SALDO FROM CONTA_CORRENTE WHERE NUM_CONTA = CONTA_NUM;
SELECT TIPO_CONTA INTO V_TIPO FROM CONTA_CORRENTE WHERE NUM_CONTA = CONTA_NUM;

    IF V_TIPO = 1 THEN
        V_SALDO := V_SALDO + V_SALDO * 0.1;
    END IF;
    IF V_SALDO > VL_SACAR THEN
        UPDATE CONTA_CORRENTE SET SALDO = (SALDO - VL_SACAR) WHERE NUM_CONTA = CONTA_NUM;
        DBMS_OUTPUT.PUT_LINE('ATUALIZADO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SALDO INSUFICIENTE');
    END IF;
    SELECT * FROM CONTA_CORRENTE;
END;


DECLARE
    V_NUM_DIAS NUMBER(2) := &NUMERODIAS;
    V_ESTADIA NUMBER(8,2);
    V_CONVENIO NUMBER(1) := &CONVENIO;
    V_TOTAL NUMBER(6,2);
BEGIN

    IF V_NUM_DIAS = 1 THEN
        V_ESTADIA := 15;
    ELSIF V_NUM_DIAS > 1 AND V_NUM_DIAS < 4 THEN
        V_ESTADIA := 10;
    ELSIF V_NUM_DIAS >3 AND V_NUM_DIAS < 8 THEN
        V_ESTADIA := 8;
    ELSIF V_NUM_DIAS > 7 THEN
        V_ESTADIA := 5;
    END IF;
    V_TOTAL := V_ESTADIA * V_NUM_DIAS;
    IF V_CONVENIO = 1 THEN 
        V_TOTAL:= V_TOTAL - V_TOTAL * 0.15;
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('VALOR A PAGAR: ' || V_TOTAL);
END;
    




